### ISSUE TITLE
Custom component removed from ESPHome 2025.2.0

### ISSUE THREAD

**Issue by uximxim** [formatBCE/Airbnk-MQTTOpenGateway#16]
The "custom" component has been removed. Consider conversion to an external component.
  https://esphome.io/guides/contributing#a-note-about-custom-components.
  - lambda: |-
      auto my_node = new AirbnkGatewayNodeComponent("xx:xx:xx:xx:xx:xx", "XXXX");
      return {my_node};

**Comment by formatBCE** [comment]
Oh, it's still used by someone?
I guess i'll have to change it to external_component...

Thanks for heads-up! It will take some time, but i'm on it.

**Comment by Corinake** [comment]
Hope you will do the fix. Thanks

**Comment by formatBCE** [comment]
> Hope you will do the fix. Thanks

Well, I'm trying. But external components have number of restrictions to usage of both BLE and MQTT. I actually am convinced by HA devs, that main integration should be changed to use BLE directly, instead of using custom BLE and MQTT. I created corresponding issue in integration repository.

**Comment by jessevallaro** [comment]
For now adding this suffices:

```
external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
```

SOURCE: https://github.com/robertklep/esphome-custom-component
